### ISSUE TITLE
Will not pull info since last update

### ISSUE THREAD

**Issue by Kadengt** [Kouzukii/ffxiv-priceinsight#31] opened 2023-11-19 17:49 UTC
Hello, The plugin Price Insight doesn't pull the price(s) anymore. I've used ALT to "retry", also right clicking the plugin and Reset Data and Reload option. The plugin seems to load fine, no error about it. I have checked the console about this and it shows an error. 

`11:48:38.354 ERR | [PlayerTrack] Failed to process lodestone requests.
11:48:38.354 ERR | System.AggregateException: One or more errors occurred. (The requested address is not valid in its context. (api.kalilistic.io:443))
11:48:38.354 ERR |  ---> System.Net.Http.HttpRequestException: The requested address is not valid in its context. (api.kalilistic.io:443)
11:48:38.354 ERR |  ---> System.Net.Sockets.SocketException (10049): The requested address is not valid in its context.
11:48:38.354 ERR |    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
11:48:38.354 ERR |    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
11:48:38.354 ERR |    at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
11:48:38.354 ERR |    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
11:48:38.354 ERR |    --- End of inner exception stack trace ---
11:48:38.354 ERR |    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
11:48:38.354 ERR |    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
11:48:38.354 ERR |    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
11:48:38.354 ERR |    at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
11:48:38.354 ERR |    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
11:48:38.354 ERR |    at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
11:48:38.354 ERR |    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
11:48:38.354 ERR |    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
11:48:38.354 ERR |    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
11:48:38.354 ERR |    at PlayerTrack.Domain.LodestoneService.GetCharacterIdsAsync(List`1 requests) in /work/repo/PlayerTrack.Domain/Services/LodestoneService.cs:line 188
11:48:38.354 ERR |    --- End of inner exception stack trace ---
11:48:38.354 ERR |    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
11:48:38.354 ERR |    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
11:48:38.354 ERR |    at PlayerTrack.Domain.LodestoneService.SendBatchRequest(List`1 batchedRequests) in /work/repo/PlayerTrack.Domain/Services/LodestoneService.cs:line 136
11:48:38.354 ERR |    at PlayerTrack.Domain.LodestoneService.ProcessRequests(Object sender, ElapsedEventArgs e) in /work/repo/PlayerTrack.Domain/Services/LodestoneService.cs:line 118`

Not sure what this is, as I've never done anything with code before, but, it just repeats this specific error everytime it updates / refreshes itself.

**Comment by Kouzukii** [comment] 2023-12-28 22:56
Duplicate of #32

**Closed by Kouzukii** 2023-12-28 22:56 UTC
